name: CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    name: "${{ matrix.configurations.name }} | ${{ matrix.configurations.config-preset }} | ${{ matrix.cmake-build-type }}"
    runs-on: ${{ matrix.configurations.os }}
    strategy:
      fail-fast: false
      matrix:
        configurations:
          - name: Ubuntu 22.04
            os: ubuntu-22.04
            config-preset: linux-clang
            build-preset: linux-clang-build
            test-preset: linux-clang-test
          - name: Ubuntu 20.04
            os: ubuntu-20.04
            config-preset: linux-clang
            build-preset: linux-clang-build
            test-preset: linux-clang-test
        cmake-build-type: [Debug]

    steps:
      - uses: actions/checkout@v3
      - uses: turtlesec-no/get-ninja@1.0.0

      - name: Install Conan
        id: conan
        uses: turtlebrowser/get-conan@main
        with:
          version: 1.60.0

      - name: Configure CMake
        shell: bash
        run: cmake --preset ${{ matrix.configurations.config-preset }} -DCMAKE_BUILD_TYPE=${{ matrix.cmake-build-type }}

      - name: Build
        shell: bash
        run: cmake --build --preset ${{ matrix.configurations.build-preset }} --config ${{ matrix.cmake-build-type }}

      - name: Test
        shell: bash
        run: ctest --preset ${{ matrix.configurations.test-preset }} -C ${{ matrix.cmake-build-type }} -VV